server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.71.207.196:3306/steam?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true

    # JavaMailSender 邮件发送的配置
  mail:
    host: smtp.qq.com
    username: 1942890632@qq.com
    password: ttqkxrzzsbicciag
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
      default-encoding: UTF-8

qinniu:
  ak: pjzQK4QnyQo44dNqXIxxkyWnYm8evx8OZKp-5gwU
  sk: Mg6pwAB95T4GBOAp_pgas6g0vJZz1XK8YYJ7EwiQ
  bucket: zhou-file
  url: http://qk1bwdbrz.hb-bkt.clouddn.com/

  #APP_ID, APP_PRIVATE_KEY, FORMAT, CHARSET, ALIPAY_PUBLIC_KEY, SIGN_TYPE
  #卖家账号：onxcvb8790@sandbox.com
Alipay:
  serverUrl: https://openapi.alipaydev.com/gateway.do
  APP_ID: 2021000116658997
  APP_PRIVATE_KEY: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCPRkUTh85+b2zdZemHbFfJ/rUen/55qONiiYyMK1z77GoWQeLF+5VJxzWODpkuGQRLRloYjUlq/02NVcvuLYLUDCvGhYjNRQNs4IDPIJ/IckaaDaoZP2iy/I5n1I+Zvl//OeD7gO0Wj2vn5jkK5xCHRd/aw5zeWMZFymst9Xf41LeXBt5f7enP+XLY6J2f35D8sblSY0poNznFLDHk+gDpV9/yg+zzd3BJx6TFyFUW8mcT2TY3FkU5b2DV/rabbDcleES1up4g8Su0uWGDg58hwjv7ZCgw3bqTbb30lQTIjw/GPVQPSge4w0yracdT1ajNGVQXDEKEX0irQqcGqgOpAgMBAAECggEASm6oLjhMh5TdiruKMeeQSAlCEPHvo0ahMqzgzmUsvlgY2Q1Lga1s5lJOuUlOPQuUFoMrBTxJWwPdR0K+WjNcl0rnZxAyfOmQmPydDn4VZG4xzZCxwMIXY30fgkOEgsvLVW29OwvEoAbMeUI6ejaGeLBNVnpvQXf/MXyyZ8Lxm9wng5VUnfg8up7ji2DghsBHNrl7g0KEeubK3en62v39/tWqSMyyimHBe5MQyCndSPNqr+GoQUGL2CstcAZVYnOS+A4zGV4vnyI3XHnIGE7WMVpA+OYQpspai7KuUKC8YM33Sb25+IGMRFY4JJ4UdZGdCM7CQVNItJk0IApsBq8UAQKBgQDH815FLtZwifZ3+g2nWIPSUHgrmUfxpE3ZcRZV5Lu9R+qPsa+Vp+ExwfMLGDsWKnwS2AL6szhDy38IZzTNPaNRHhZ/mVGW2mOacmZM+pLy07s6ax9UoDzUXigQLA0ZLujoUQCOrqYnmQHKxiopqoD2gWSpCHEGtzeiX1g024L/gQKBgQC3b8VhM/FHhW4Omx7vRhi+PJPD1uHEn1g3QwSz5QxO0+PCeom+BP0VN/eEFONlNFLfQChehEwbFiOc8c1DEeFuENEn0P4MRAzl9KMQMDGUuzM88KmR0dsfvkRZDoR/xf5d1nNeZx4dJjYIlbuznp+LM4DqENfOe7eSvNzEtDsYKQKBgEfBZ8BOKbijWib+Pq4ijtQH+sgyruXh/+obsldKybEIwP2mV4vOfntbzfvaS0IOJw6gJJmRfYye18zNNN6+0wBGWu6Zt/T6FKqViW7wsZGhOFyjms/E3W+dBqWfGWhDNGRCxX9u38PwHfuGGBVx0ewkzVn35I/zamzD6KS3bhCBAoGALzDV+ne+bsPo2GEXyD6kRuyWpx803byQmUbogs8+J1ljkrirjvMBmN/ZEWW+Sl73ou+Ccy5d1eoQJ2Qdhk+nSwWQiUm+0bEAEHirKpL7bmPqfpb7SMRQNw5fzvlpJOXu1n1BGNw2ZxFZfUPoEgGQ0eLiG1VR75DsXRexQ/mJ6mECgYEAtSPOYOGwAFJZH7itLjEhDESdzaYlhgqxaywHt5iStWHZr42cfi/2O8fO+GUQc3ObalDvugDDa1mRZm8Ppb/prklXE1W9ipW0oYXnTFSqpS6+dHnjdTdboAvjl+8irJEU/JB5LSy/EQq5gE7VZnrbz4b1nilvkienWlTVUafaeYQ=
  FORMAT: json
  CHARSET: UTF-8
  ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi82bO5joBEUD+iSJg+kH4QX3u3yqA8BnXNt6MJJ+WoqvcEWIJaCbg23nMId0W4gsupySDz3OEmqJBWey2cNpF0eRXUsYEI99jP9prFQHZQgzmB+Mf3UXt/DqFD0s/qPmCdCAoasBBk0IJojmN9kzbm9fcPByilVaGpBv7eY+7hIpkdJClgpQiVMEMgkIiKqIyjl82HWLL9iZzhsn+5bOR2E8o6Vc0g6x1YMSJqyShkRBASF7w10eHjFAeXi3UeeLKwO+F+ulmN7SnOPEs5tLVtcHCfNHjqr7J+AP4K0LTKKynh5cCkHZjDVCoTaN2fVuIDDvuqsyqLSug3Log8Q60QIDAQAB
  SIGN_TYPE: RSA2


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.qf.pojo
